# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d98f341ed66a1eba173f0311b2cb89f89536af17f95b689cd1bad5481e686b3d9b05012b6dc10735cfc01198ff174ce3075e2363146ee680ab5d9763916c859e

test:
  secret_key_base: 78b0bdeb6ebea7a6b30b965e16715e380b5c78753329c0bbd631fef552cc5b965c1a3f6130f1c73a7fa646de94fab32615731a07ef8ba0986238ef926f8b8baf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
